[workspace]
members = [
    "crates/flushdb-proto",
    "crates/flushdb-types",
    "crates/flushdb-wal",
    "crates/flushdb-engine",
    "crates/flushdb-server",
    "crates/flushdb-test",
]
resolver = "2"

[workspace.dependencies]
tokio = { version = "1", features = ["full"] }
tonic = "0.14"
prost = "0.14"
tonic-build = "0.14"
tonic-prost = "0.14"
tonic-prost-build = "0.14"
bytes = "1"
crc32fast = "1"
thiserror = "2"
serde = { version = "1", features = ["derive"] }
serde_json = "1"
rand = "0.9"
tracing = "0.1"
uuid = { version = "1", features = ["v7"] }
async-trait = "0.1"
tempfile = "3"
byteorder = "1"
moka = { version = "0.12", features = ["sync"] }
aws-sdk-s3 = "1"
aws-config = "1"
tracing-subscriber = { version = "0.3", features = ["env-filter", "json"] }
metrics = "0.24"
metrics-exporter-prometheus = "0.16"
parking_lot = "0.12"
dashmap = "6"
testcontainers = "0.23"
testcontainers-modules = { version = "0.11", features = ["minio"] }
fnv = "1"
futures = "0.3"
tokio-stream = "0.1"
