[package]
name = "flushdb-types"
version = "0.1.0"
edition = "2021"

[dependencies]
bytes = { workspace = true }
thiserror = { workspace = true }
serde = { workspace = true }
tokio = { workspace = true }
uuid = { workspace = true }
async-trait = { workspace = true }
byteorder = { workspace = true }
tracing = { workspace = true }

[dev-dependencies]
tempfile = { workspace = true }
