[package]
name = "flushdb-wal"
version = "0.1.0"
edition = "2021"

[dependencies]
flushdb-types = { path = "../flushdb-types" }
bytes = { workspace = true }
crc32fast = { workspace = true }
tokio = { workspace = true }
tracing = { workspace = true }

[dev-dependencies]
tempfile = { workspace = true }
tokio = { workspace = true }
